scenarios:
  1:
    trained: True
    tgt_skill: "Punch(robot,block,obstruction_rec)"
    failed_skill: "ReachToGrasp"
    failed_objects: "robot,grasp_block"
    basic_type: "block"
    max_rl_steps: 10
    rl_static_steps: 3
    max_env_steps: 200
    train_objects: "robot,grasp_block,obstruction_rec"
    basic_objects: "grasp_block"
    skill_learning_cfg_settings:
      scenario: "1"
      specified_task_path: "config/specified_tasks/blocked_stacking"
      rl_config: "config/pure_rl/blocked_stacking_ppoc_sc1.yaml"
      rl_dataset_path: "training_data/blocked_stacking/RL_data/scenario_1"
      max_env_steps: 240
      num_train_episodes_rl: 100
      num_envs: 32
      num_eval_envs: 32
      obstruction1_blocking_grasp: True
      obstruction1_blocking_stacking: False
    planner_learning_cfg_settings:
      num_envs: 1
      scenario: "1"
      middle_state_method: "naive_init"
      real_scenario_name: "sc1_pre_n1"
      num_middle_states: 20
      rl_config: "config/pure_rl/blocked_stacking_ppoc_sc1.yaml"
      pre_trained_policy_path: "trained_policies/runs/skill_1127_sc1_seed4/best_ppo_ckpt.pt"
      predicate_config: "config/predicates/blocked_stacking_confined_enu_sc1.yaml"
      obstruction1_blocking_grasp: True
      obstruction1_blocking_stacking: False
      blocked2d_reach_drift_trans: 0.01
      blocked2d_reach_drift_rot: 0.003
      pred_net_save_dir: "skill_1206_sc12_2_pred_nets_seed4"
      force_skip_pred_learning: True
      num_train_episodes_planner: 1000
      num_failed_episodes_planner: 40
      num_train_episodes_planner_before_dreaming: 100
      pred_search_num_trajectories: 100
      max_env_steps: 300
      planner_dataset_path: "training_data/blocked_stacking/Planner_data/scenario1"
      planner_num_traj: 5
  2:
    trained: False
    tgt_skill: "Wiggle(robot,block,obstruction_tra)"
    failed_skill: "ReachToGrasp_Punch"
    failed_objects: "robot,grasp_block,obstruction_rec"
    basic_objects: "grasp_block,grasp_block"
    basic_type: "block"
    max_rl_steps: 8
    rl_static_steps: 3
    max_skill_steps: 200
    train_objects: "robot,grasp_block,obstruction_tra"
    skill_learning_cfg_settings:
      scenario: "1,2"
      pre_trained_policy_path: "trained_policies/runs/skill_1128_sc12_2_seed4/best_ppo_ckpt.pt"
      specified_task_path: "config/specified_tasks/blocked_stacking"
      rl_config: "config/pure_rl/blocked_stacking_ppoc_sc12_2.yaml"
      rl_dataset_path: "training_data/blocked_stacking/RL_data/scenario12_2"
      max_env_steps: 240
      num_train_episodes_rl: 100
      num_envs: 32
      num_eval_envs: 32
      obstruction1_blocking_grasp: True
      obstruction1_blocking_stacking: False
      obstruction2_blocking_grasp: True
      obstruction2_blocking_stacking: False
    planner_learning_cfg_settings:
      num_envs: 1
      scenario: "1,2"
      middle_state_method: "naive_init"
      real_scenario_name: "sc1_pre_n1_sc2_pre_n1"
      num_middle_states: 20
      rl_config: "config/pure_rl/blocked_stacking_ppoc_sc12_2.yaml"
      pre_trained_policy_path: "trained_policies/runs/skill_1128_sc12_2_seed4/best_ppo_ckpt.pt"
      predicate_config: "config/predicates/blocked_stacking_confined_enu_sc12_2.yaml"
      obstruction1_blocking_grasp: True
      obstruction1_blocking_stacking: False
      obstruction2_blocking_grasp: True
      obstruction2_blocking_stacking: False
      blocked2d_reach_drift_trans: 0.01
      blocked2d_reach_drift_rot: 0.003
      pred_net_save_dir: "skill_1206_sc12_2_pred_nets_seed4"
      force_skip_pred_learning: True
      quantify_basic: False
      filter_preconditions: True
      num_train_episodes_planner: 2000
      num_failed_episodes_planner: 160
      num_train_episodes_planner_before_dreaming: 100
      pred_search_num_trajectories: 400
      max_env_steps: 400
      planner_dataset_path: "training_data/blocked_stacking/Planner_data/scenario12_2"
      planner_num_traj: 200
