scenarios:
  1:
    trained: False
    tgt_skill: "Push(robot,goal,can)"
    failed_skill: "PlaceBox"
    failed_objects: "robot,box,box_goal"
    basic_type: "goal"
    max_rl_steps: 8
    rl_static_steps: 3
    max_skill_steps: 3500
    max_env_steps: 3500
    train_objects: "robot,box_goal,can"
    basic_objects: "box_goal"
    known_invalid_sc: "sc1_pre_n3"
    skill_learning_cfg_settings:
      scenario: "1"
      dreaming_noise_base_var: 0.0
      specified_task_path: "config/specified_tasks/cluttered_room"
      rl_config: "config/pure_rl/cluttered_room_ppoc_sc1.yaml"
      rl_dataset_path: "training_data/cluttered_room/RL_data/scenario_1"
      intrinsic_reward_path: "src/skill_refactor/approaches/intrinsic_reward/cluttered_room_sc1.py"
      planner_eval: False
      partial_planner_eval: True
      can_blocking_target1: False
      can_blocking_target2: True
      max_env_steps: 3500
      num_train_episodes_rl: 80
      num_envs: 512
      num_eval_envs: 16
    planner_learning_cfg_settings:
      num_envs: 1
      scenario: "1"
      middle_state_method: "naive_init"
      real_scenario_name: "sc1_pre_n4"
      num_middle_states: 100
      pre_trained_policy_path: "trained_policies/c_learning_0116_n8_cluttered_room_ppoc_sc1_intrinsic/best_ppo_ckpt.pt"
      specified_task_path: "config/specified_tasks/cluttered_room"
      predicate_config: "config/predicates/cluttered_room_confined_enu_sc1.yaml"
      rl_config: "config/pure_rl/cluttered_room_ppoc_sc1.yaml"
      dreaming_noise_base_var: 0.0
      clamp_xy_to_radius: 0.1
      force_skip_pred_learning: True
      can_blocking_target1: False
      can_blocking_target2: True
      num_train_episodes_planner: 400
      num_failed_episodes_planner: 40
      num_train_episodes_planner_before_dreaming: 100
      pred_search_num_trajectories: 200
      max_env_steps: 7000
      planner_dataset_path: "training_data/cluttered_room/Planner_data/scenario1"
      planner_num_traj: 5
