scenarios:
  1:
    trained: True
    tgt_skill: "Pull(robot,hammer,drawer)"
    failed_skill: "HandReachToGrasp"
    failed_objects: "robot,grasp_hammer"
    basic_type: "hammer"
    max_rl_steps: 16
    rl_static_steps: 3
    max_skill_steps: 250
    max_env_steps: 550
    train_objects: "robot,grasp_hammer,drawer"
    basic_objects: "grasp_hammer"
    skill_learning_cfg_settings:
      scenario: "1"
      dreaming_noise_base_var: 0.0
      specified_task_path: "config/specified_tasks/cluttered_drawer"
      rl_config: "config/pure_rl/cluttered_drawer_ppoc_sc1.yaml"
      rl_dataset_path: "training_data/cluttered_drawer/RL_data/scenario_1"
      planner_eval: True
      partial_planner_eval: True
      max_env_steps: 550
      num_train_episodes_rl: 50
      num_envs: 4096
      num_eval_envs: 16
      drawer_blocking_grasp: True
      drawer_blocking_stacking: False
    planner_learning_cfg_settings:
      num_envs: 16
      scenario: "1"
      dreaming_noise_base_var: 0.0
      middle_state_method: "naive_init"
      real_scenario_name: "sc1_pre_n1"
      num_middle_states: 20
      pre_trained_policy_path: "trained_policies/runs/skill_1231_sc1_seed0/best_ppo_ckpt.pt"
      predicate_config: "config/predicates/cluttered_drawer_confined_enu_sc1.yaml"
      rl_config: "config/pure_rl/cluttered_drawer_ppoc_sc1.yaml"
      drawer_blocking_grasp: True
      drawer_blocking_stacking: False
      pred_net_save_dir: "c_drawer_sc12_pred_nets_seed3"
      force_skip_pred_learning: True
      num_train_episodes_planner: 1000
      num_failed_episodes_planner: 40
      num_train_episodes_planner_before_dreaming: 100
      pred_search_num_trajectories: 100
      max_env_steps: 550
      planner_dataset_path: "training_data/cluttered_drawer/Planner_data/scenario1"
      planner_num_traj: 5
  2:
    trained: False
    tgt_skill: "Wiggle(robot,hammer,block)"
    failed_skill: "HandReachToGrasp"
    failed_objects: "robot,grasp_hammer"
    basic_objects: "grasp_hammer,grasp_hammer"
    basic_type: "hammer"
    max_rl_steps: 12
    rl_static_steps: 3
    max_skill_steps: 700
    train_objects: "robot,grasp_hammer,block"
    skill_learning_cfg_settings:
      scenario: "1,2"
      dreaming_noise_base_var: 0.0
      specified_task_path: "config/specified_tasks/cluttered_drawer"
      rl_config: "config/pure_rl/cluttered_drawer_ppoc_sc12_2.yaml"
      rl_dataset_path: "training_data/cluttered_drawer/RL_data/scenario12_2"
      planner_eval: True
      partial_planner_eval: True
      max_env_steps: 600
      num_train_episodes_rl: 200
      num_envs: 4096
      num_eval_envs: 16
      drawer_blocking_grasp: True
      drawer_blocking_stacking: False
      block_blocking_grasp: True
      block_blocking_stacking: False
    planner_learning_cfg_settings:
      num_envs: 8
      scenario: "1,2"
      rl_next_skill: "BodyReachToGrasp"
      dreaming_noise_base_var: 0.0
      middle_state_method: "naive_init"
      specified_task_path: "config/specified_tasks/cluttered_drawer"
      real_scenario_name: "sc1_pre_n1_sc2_pre_n1"
      num_middle_states: 20
      rl_config: "config/pure_rl/cluttered_drawer_ppoc_sc12_2.yaml"
      pre_trained_policy_path: "trained_policies/runs/skill_0102_sc12_2_seed0/best_ppo_ckpt.pt"
      predicate_config: "config/predicates/cluttered_drawer_confined_enu_sc12_2.yaml"
      rl_config: "config/pure_rl/cluttered_drawer_ppoc_sc12_2.yaml"
      drawer_blocking_grasp: True
      drawer_blocking_stacking: False
      block_blocking_grasp: True
      block_blocking_stacking: False
      pred_net_save_dir: "c_drawer_sc12_pred_nets_seed3"
      force_skip_pred_learning: True
      quantify_basic: False
      max_consecutive_failures: 8
      num_train_episodes_planner: 1280
      num_failed_episodes_planner: 128
      num_train_episodes_planner_before_dreaming: 100
      pred_search_num_trajectories: 100
      max_env_steps: 800
      planner_dataset_path: "training_data/cluttered_drawer/Planner_data/scenario12_2"
      planner_num_traj: 5