scenarios:
  1:
    trained: True
    tgt_skill: "IcyDrive(robot,transport_obj,icy_region)"
    failed_skill: "GoToPickObject"
    failed_objects: "robot,transport_obj1"
    basic_type: "transport_obj"
    max_rl_steps: 30
    rl_static_steps: 20
    max_skill_steps: 1500
    train_objects: "robot,transport_obj1,icy_region"
    basic_objects: "transport_obj1"
    skill_learning_cfg_settings:
      scenario: "1"
      specified_task_path: "config/specified_tasks/icy_transport"
      rl_config: "config/pure_rl/icy_transport_ppoc_sc1.yaml"
      rl_dataset_path: "training_data/icy_transport/RL_data/scenario_1"
      planner_eval: True
      partial_planner_eval: True
      max_env_steps: 3000
      num_train_episodes_rl: 50
      num_envs: 32
      num_eval_envs: 8
      icy_infront_of_transport1: True
      icy_infront_of_transport2: False
      icy_infront_of_target: False
    planner_learning_cfg_settings:
      num_envs: 8
      scenario: "1"
      middle_state_method: "naive_init"
      specified_task_path: "config/specified_tasks/icy_transport"
      real_scenario_name: "sc1_pre_n1"
      num_middle_states: 20
      rl_config: "config/pure_rl/icy_transport_ppoc_sc1.yaml"
      pre_trained_policy_path: "trained_policies/runs/skill_0101_i_transport_sc1_seed0/best_ppo_ckpt.pt"
      predicate_config: "config/predicates/icy_transport_confined_enu_sc1.yaml"
      force_skip_pred_learning: True
      icy_infront_of_transport1: True
      icy_infront_of_transport2: False
      icy_infront_of_target: False
      icy_transport_reach_drift_trans: 0.01
      icy_transport_reach_drift_rot: 0.003
      pred_net_save_dir: "skill_0101_i_transport_sc12_2_pred_nets_seed0"
      num_train_episodes_planner: 600
      num_failed_episodes_planner: 12
      num_train_episodes_planner_before_dreaming: 100
      pred_search_num_trajectories: 50
      pred_search_operator_learning_out_of_sample_penalty: 0.0
      max_env_steps: 3000
      planner_dataset_path: "training_data/icy_transport/Planner_data/scenario1"
      planner_num_traj: 5
  2:
    trained: False
    tgt_skill: "MuddyDrive(robot,transport_obj,muddy_region)"
    failed_skill: "GoToPickObject"
    failed_objects: "robot,transport_obj1"
    basic_type: "transport_obj"
    max_rl_steps: 30
    rl_static_steps: 20
    max_skill_steps: 1500
    train_objects: "robot,transport_obj1,muddy_region"
    basic_objects: "transport_obj2,transport_obj1"
    skill_learning_cfg_settings:
      scenario: "1,2"
      specified_task_path: "config/specified_tasks/icy_transport"
      rl_config: "config/pure_rl/icy_transport_ppoc_sc12_2.yaml"
      pre_trained_policy_path: "trained_policies/runs/skill_0101_i_transport_sc12_2_seed0/best_ppo_ckpt.pt"
      rl_dataset_path: "training_data/icy_transport/RL_data/scenario_12_2"
      planner_eval: True
      partial_planner_eval: True
      dreaming_noise_base_var: 0.0
      max_env_steps: 3000
      num_train_episodes_rl: 100
      num_envs: 32
      num_eval_envs: 8
      icy_infront_of_transport1: False
      icy_infront_of_transport2: True
      icy_infront_of_target: False
      muddy_infront_of_transport1: True
      muddy_infront_of_transport2: False
      muddy_infront_of_target: False
    planner_learning_cfg_settings:
      num_envs: 1
      scenario: "1,2"
      middle_state_method: "naive_init"
      real_scenario_name: "sc1_pre_n2_sc2_pre_n1"
      num_middle_states: 20
      specified_task_path: "config/specified_tasks/icy_transport"
      rl_config: "config/pure_rl/icy_transport_ppoc_sc12_2.yaml"
      predicate_config: "config/predicates/icy_transport_confined_enu_sc12_2.yaml"
      pre_trained_policy_path: "trained_policies/runs/skill_0101_i_transport_sc12_2_seed0/best_ppo_ckpt.pt"
      icy_infront_of_transport1: False
      icy_infront_of_transport2: True
      icy_infront_of_target: False
      muddy_infront_of_transport1: True
      muddy_infront_of_transport2: False
      muddy_infront_of_target: False
      icy_transport_reach_drift_trans: 0.01
      icy_transport_reach_drift_rot: 0.003
      pred_net_save_dir: "skill_0101_i_transport_sc12_2_pred_nets_seed0"
      force_skip_pred_learning: True
      quantify_basic: False
      num_train_episodes_planner: 2000
      num_failed_episodes_planner: 160
      num_train_episodes_planner_before_dreaming: 100
      pred_search_num_trajectories: 400
      max_env_steps: 5000
      planner_dataset_path: "training_data/icy_transport/Planner_data/scenario12_2"
      planner_num_traj: 20