policy_type: "PPO"
num_envs: 32
update_epochs: 8
num_minibatches: 20
total_timesteps: 1000000
num_steps: 8
c_buffer_size: 12000
num_eval_envs: 8
finite_horizon_gae: True
trivial_classifier: True
clip_coef: 0.1
resume_ppo: ""
resume_buffer: ""