policy_type: "PPO"
num_envs: 32
update_epochs: 8
num_minibatches: 20
total_timesteps: 200000
num_steps: 16
finite_horizon_gae: False
trivial_classifier: True
anneal_lr: False
clip_coef: 0.1
resume_ppo: ""