scenarios:
  1:
    trained: False
    tgt_skill: "IcyDrive(robot,transport_obj,icy_region)"
    failed_skill: "GoToPickObject"
    failed_objects: "robot,transport_obj1"
    basic_type: "transport_obj"
    max_rl_steps: 30
    rl_static_steps: 20
    max_skill_steps: 1500
    train_objects: "robot,transport_obj1,icy_region"
    basic_objects: "transport_obj1"
    real_scenario_name: "sc1_pre_n1"
    specified_task_path: "config/specified_tasks/icy_transport"
    rl_config: "config/pure_rl/icy_transport_ppoc_sc1.yaml"
    rl_dataset_path: "training_data/icy_transport/RL_data/scenario_1"
    failure_learning_cfg_settings:
      num_envs: 8
      scenario: "1"
      middle_state_method: "naive_init"
      specified_task_path: "config/specified_tasks/icy_transport"
      rl_config: "config/pure_rl/icy_transport_ppoc_sc1.yaml"
      failure_nn_config: "config/predicates/icy_transport_failure_det_sc1.yaml"
      icy_infront_of_transport1: True
      icy_infront_of_transport2: False
      icy_infront_of_target: False
      num_train_episodes_planner: 75
      num_train_episodes_planner_before_dreaming: 13
      max_env_steps: 4000
      planner_dataset_path: "training_data/icy_transport/Planner_data/scenario1"
      failured_det_operator_objects:
        GoToPickObject:
          - 0
          - 1
        GoToPlaceObject:
          - 0
          - 2